# dev yaml, rename later to docker-compose.dev.yml to distinct from prod
# diff is bind volume on flask app, debug enabled (hot reload) and unsafe neo4j pwd 
services:
  webapp:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-app   
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      FLASK_ENV: development 
    restart:
      always

  job-service:
    build: ./job-service
    container_name: job-service
    ports:
      - "8000:80"
    volumes:
      - ./job-service/app:/app
    #depends_on:
      #neo4j:
      #  condition: service_healthy
    restart: always

  db-service:
    build:
      context: ./db-service
    container_name: db-service
    volumes:
      - ./db-service:/app
    environment:
      - NEO4J_URI=bolt://neo4j-db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test1234
    ports:
      - "8001:80"
    depends_on:
      - neo4j
    restart: always

  neo4j:
    image: neo4j:5.24-community-bullseye
    container_name: neo4j-db
    volumes:
      - neo4j_data:/data  
      - neo4j_logs:/logs  
      - ./create-indexes.bash:/startup/create-indexes.bash
      - ./custom-docker-entrypoint.sh:/startup/docker-entrypoint.sh
    ports:
      - "7474:7474"   # web interface
      - "7687:7687"   # Bolt protocol (used by drivers)
    environment:
      - NEO4J_AUTH=neo4j/test1234 # not secure
      - EXTENSION_SCRIPT=/startup/create-indexes.bash
      - NEO4J_PLUGINS=["apoc"]
    restart:
      always
    healthcheck:
      test: wget http://localhost:7687 || exit 1
      interval: 10s
      timeout: 30s
      retries: 6
      start_period: 15s
    


volumes:
  neo4j_data:
  neo4j_logs: